steps:
  - label: ":go: go mod graph"
    command: | 
      printf "$(go mod graph)\n\n$(go list -mod=readonly -e -m all)" > .debricked-go-dependencies.txt
    plugins:
      - golang#v2.0.0:
          version: 1.17
    artifact_paths: "**/.debricked-go-dependencies.txt"
  - wait
  - label: ":shield: Debricked"
    command:
      - buildkite-agent artifact download "**.debricked-go-dependencies.txt" .
      - bash /buildkite.sh
    plugins:
      - docker#v3.3.0:
          image: "debricked/debricked-scan"
          mount-buildkite-agent: true
          environment:
              - "DEBRICKED_TOKEN"
              - "BUILDKITE_REPO"
              - "BUILDKITE_COMMIT"
              - "BUILDKITE_BRANCH"
          entrypoint: ""
          shell : ["/bin/sh", "-e", "-c"]
